// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
	BOT_TOKEN: string;
	WEBHOOK_URL: string;
	SECRET_TOKEN: string;
	DROP_PENDING_UPDATES: 'True' | 'False';
}
